development:
  secret_key_base: 28495e9d5b413be7eba10b624c30e8df258632abe807fec07ffa3d3de740da245ab2f1623223de44e15bdb5d685e3a10c35dfb99a8f51aacf2372a4cead03224

test:
  secret_key_base: 28495e9d5b413be7eba10b624c30e8df258632abe807fec07ffa3d3de740da245ab2f1623223de44e15bdb5d685e3a10c35dfb99a8f51aacf2372a4cead03224

production:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") if Rails.env.production? %>
